### ISSUE TITLE
导入新的配置文件出错

### ISSUE THREAD

**Issue by import-yuefeng** [knight42/Yuki-cli#3]
yuki开发者, 我在当前目录下创建了一个test.repo, 然后写入了如下配置文件(隐去ip),
{
  "bindIP": "test",
  "envs": {
          "RSYNC_HOST": "mirrors.xtom.com",
          "RSYNC_PATH": "repo/sb/"
  },
  "image": "ustcmirror/rsync:latest",
  "interval": "45 1 * * *",
  "logRotCycle": 10,
  "name": "sb",
  "storageDir": "/srv/repo/sb/"
}
然后通过yuki import test.repo , 但是test.repo反馈了一个比较奇怪的错误, 我不是很理解, 所以特来询问.
反馈的错误是: Unmarshal type error: expected=[]*core.Repository, got=object, offset=1
yuki版本: yuki 0.1.0

**Comment by knight42** [comment]
文件里的内容要求是一个数组。改为 `[{...}]` 应该就可以了。

**Comment by import-yuefeng** [comment]
非常感谢, 已经好啦~
